name: scala-steward
on:
  push:
    branches: [ master ]
  schedule:
  - cron: '0 0 * * 1,4'
  workflow_dispatch:
concurrency:
  group: scala-steward
jobs:
  scala-steward:
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner == 'wartremover' }}
    timeout-minutes: 30
    steps:
    - uses: actions/setup-java@v5
      with:
        java-version: 21
        distribution: temurin
    - name: Generate token
      id: generate_token
      uses: actions/create-github-app-token@1b10c78c7865c340bc4f6099eb2f838309f1e8c3 # v3.1.1
      with:
        client-id: 89668
        private-key: ${{ secrets.WARTREMOVER_BOT_KEY }}
    - name: Launch Scala Steward
      uses: scala-steward-org/scala-steward-action@b186ab858ce163f9af7b016fac32cfb3f2c2f503 # v2.88.0
      with:
        github-token: ${{ steps.generate_token.outputs.token }}
        author-email: "74847867+wartremover-bot[bot]@users.noreply.github.com"
        author-name: wartremover-bot[bot]
